// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Xác thực user. Nếu thành công, gửi OTP qua email để xác thực 2 bước.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP đã gửi về email",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Dữ liệu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Sai email hoặc mật khẩu",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "403": {
                        "description": "Tài khoản chưa xác thực email",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy thông tin profile của user đang đăng nhập (yêu cầu JWT).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_gateway_handler.userResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/auth/password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Đổi mật khẩu. Yêu cầu JWT và mật khẩu hiện tại đúng.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "description": "Mật khẩu cũ và mới",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Đổi mật khẩu thành công",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Mật khẩu hiện tại sai",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Tạo tài khoản mới. Password được hash bằng bcrypt (cost=12). Trả về 409 nếu email/username đã tồn tại.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Đăng ký thành công",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_gateway_handler.userResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Dữ liệu không hợp lệ",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "409": {
                        "description": "Email hoặc username đã tồn tại",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/scans": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách tất cả scan job của user hiện tại (tối đa 50, sắp xếp mới nhất).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scans"
                ],
                "summary": "List scan jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_gateway_handler.scanListItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo scan job mới (status=pending) và đẩy vào RabbitMQ để xử lý bất đồng bộ. Trả về 202 Accepted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scans"
                ],
                "summary": "Create a scan job",
                "parameters": [
                    {
                        "description": "Target ID và loại scan",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.createScanRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Scan job đã được chấp nhận",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_gateway_handler.scanJobResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Dữ liệu không hợp lệ hoặc SSRF blocked",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Target không tồn tại",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "429": {
                        "description": "Quá nhiều request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/scans/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy chi tiết một scan job theo ID. User phải là chủ sở hữu.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scans"
                ],
                "summary": "Get scan job detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_gateway_handler.scanListItem"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Scan không tồn tại",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/scans/{id}/report": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy báo cáo lỗ hổng của một scan đã hoàn thành. Kiểm tra quyền sở hữu qua PG rồi lấy dữ liệu từ MongoDB.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Get scan report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_gateway_handler.ReportResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Scan chưa hoàn thành",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Scan hoặc report không tồn tại",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/scans/{id}/triage": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách triage rules của một scan (mà user sở hữu).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "triage"
                ],
                "summary": "Get triage rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Danh sách triage rules",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Scan không tồn tại",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/scans/{id}/triage/{fingerprint}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo hoặc cập nhật triage rule cho một lỗ hổng (theo fingerprint).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "triage"
                ],
                "summary": "Upsert triage rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scan Job ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fingerprint của vulnerability",
                        "name": "fingerprint",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Triage rule data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_internal_domain_model.TriageRuleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cập nhật thành công",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        },
        "/targets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy danh sách tất cả target của user hiện tại.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "List scan targets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_gateway_handler.targetResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo một target mới để scan. URL được kiểm tra SSRF. Trả về 409 nếu URL đã tồn tại.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "Create a scan target",
                "parameters": [
                    {
                        "description": "Thông tin target",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.createTargetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tạo thành công",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_gateway_handler.targetResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "URL không hợp lệ hoặc SSRF blocked",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "409": {
                        "description": "Target URL đã tồn tại",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_nexussec_nexussec_pkg_response.JSONResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_nexussec_nexussec_internal_domain_model.TriageRuleRequest": {
            "type": "object",
            "properties": {
                "is_false_positive": {
                    "type": "boolean"
                },
                "is_muted": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                }
            }
        },
        "github_com_nexussec_nexussec_pkg_response.JSONResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_gateway_handler.CleanVulnerability": {
            "type": "object",
            "properties": {
                "cvss_score": {
                    "type": "number"
                },
                "cwe": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "remediation": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "source_tool": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "vuln_id": {
                    "type": "string"
                }
            }
        },
        "internal_gateway_handler.ReportResponse": {
            "type": "object",
            "properties": {
                "scan_id": {
                    "type": "string"
                },
                "summary": {
                    "$ref": "#/definitions/internal_gateway_handler.SummaryResponse"
                },
                "vulnerabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_gateway_handler.CleanVulnerability"
                    }
                }
            }
        },
        "internal_gateway_handler.SummaryResponse": {
            "type": "object",
            "properties": {
                "critical": {
                    "type": "integer"
                },
                "high": {
                    "type": "integer"
                },
                "info": {
                    "type": "integer"
                },
                "low": {
                    "type": "integer"
                },
                "medium": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_gateway_handler.changePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "internal_gateway_handler.createScanRequest": {
            "type": "object",
            "required": [
                "scan_type",
                "target_id"
            ],
            "properties": {
                "scan_type": {
                    "type": "string",
                    "enum": [
                        "zap",
                        "nmap",
                        "full"
                    ]
                },
                "target_id": {
                    "type": "string"
                }
            }
        },
        "internal_gateway_handler.createTargetRequest": {
            "type": "object",
            "required": [
                "base_url",
                "name"
            ],
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "internal_gateway_handler.loginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_gateway_handler.registerRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "internal_gateway_handler.scanJobResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "scan_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target_url": {
                    "type": "string"
                }
            }
        },
        "internal_gateway_handler.scanListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "scan_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target_url": {
                    "type": "string"
                }
            }
        },
        "internal_gateway_handler.targetResponse": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_gateway_handler.userResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Nhập: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "NexusSec API",
	Description:      "Security scanning platform — manages targets, scan jobs, reports, and triage rules.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
